version: '3.8'

services:
  olist-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olist_mlops_api
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./artifacts:/app/artifacts
    environment:
      - ENV=production
    restart: always